name: courtconnect
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router:
  shared_preferences: ^2.2.3
  dio:
  flutter_svg: ^2.0.16
  lottie:
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  get:
  fluttertoast:
  pinput: ^5.0.1
  image_picker:
  mime_type: ^1.0.1
  flutter_widget_from_html:
  flutter_spinkit: ^5.2.1


  flutter_local_notifications: ^18.0.1
  badges:

  multiselect: ^0.1.1
  connectivity_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  flutter_gen_runner: null



flutter_gen:
  output: lib/global/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    lottie: true
    #===========>>>>>>>>>> Flutter Gen Code ==============>>>>>>>>>>>
    # dart pub global activate flutter_gen
    # flutter pub run build_runner build --delete-conflicting-outputs
#    dart run build_runner build

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/icons/
      - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat-Regular
       fonts:
         - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
